name: Patch Revanced 
on:
  workflow_dispatch:

jobs:
  build:
    name: Patch Revanced 
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        app: 
          - youtube
          - youtube-music
          - reddit

    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.38"

    - name: Install Dependencies
      run: cpanm --installdeps --notest .

    - name: Patch Revanced
      run: perl revanced.pl ${{ matrix.app }}
